service:
  name: faas-weekly-summary

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  generateWeeklySummary:
    handler: handler.generateWeeklySummary
    events:
      - schedule:
        name: weekly-summary-schedule
        description: "Weekly function run for generate weekly summary"
        # Mondays, 1:11 AM
        rate: cron(11 1 * * 1)
